[build]
  publish = "public"
  command = "hugo --minify --baseURL $URL"

[context.production.environment]
  HUGO_VERSION = "0.56.3"

[context.deploy-preview]
  command = "hugo --minify --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.56.3"
